workflows:
  android-workflow:
    name: Android Build
    instance_type: linux_x2
    max_build_duration: 60

    environment:
      vars:
        JAVA_VERSION: "17"
      # No "android:" block here — Codemagic YAML does not support it.

    scripts:
      - name: Install Java
        script: |
          sudo update-alternatives --set java /usr/lib/jvm/java-17-openjdk-amd64/bin/java
          java -version

      - name: Clean project
        script: ./gradlew clean

      - name: Build Debug APK
        script: ./gradlew assembleDebug

      - name: Build Release APK
        script: ./gradlew assembleRelease

    artifacts:
      - app/build/outputs/**/*.apk
      - app/build/outputs/**/*.aab

    publishing:
      email:
        recipients:
          - your-email@example.com
