
workflows:
  android-workflow:
    name: Android Build
    max_build_duration: 60
    instance_type: mac_mini_m1
    scripts:
      - name: Build Android Release
        script: | 
          gradle assembleRelease
    artifacts:
      - app/build/outputs/apk/**/*.apk
